# Generated by Django 4.0.2 on 2022-04-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('singer', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=200)),
                ('movie', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='documents')),
                ('song', models.FileField(upload_to='song_files')),
            ],
        ),
    ]
