# Generated by Django 4.0.2 on 2022-05-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=500),
        ),
    ]
