# Generated by Django 4.0.2 on 2022-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats2', '0005_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('music', models.CharField(max_length=1000)),
            ],
        ),
    ]
