# Generated by Django 4.0.2 on 2022-05-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats2', '0006_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='credit',
        ),
    ]
